name: 发布新版本
on:
  workflow_dispatch:
permissions: write-all
jobs:
  publish:
    name: 发布新版本
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: npm-cache
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: 安装依赖
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install

      - name: 更新制作人员列表
        run: node ${{ github.workspace }}/.github/workflows/scripts/update_authors.js
      - name: 检查版本号冲突
        run: node ${{ github.workspace }}/.github/workflows/scripts/check_version.js
      - name: 检查更新日志并转markdown
        run: |
          node ${{ github.workspace }}/.github/workflows/scripts/check_changelog.js
      # 其他预处理以后要用的时候在上方添加

      - name: 为网站构建
        run: npm run build:website

      - name: 发布到 GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: gh-pages
          build_dir: ./dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 推送到Gitee
        run: |
          git config --global user.name "github action"
          git config --global user.email "action_bot@github.com."
          git clone https://gitee.com/nuitka-commander/nuitka-commander.git
          cp -r ./dist/* ./nuitka-commander/
          cd ./nuitka-commander
          git add .
          git commit -m "Update from GitHub Actions"
          git push https://oauth2:${{ secrets.GITEE_TOKEN }}@gitee.com/nuitka-commander/nuitka-commander.git

      - name: 部署Gitee Page
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: ${{secrets.GITEE_USERNAME}}
          gitee-password: ${{secrets.GITEE_PASSWORD}}
          gitee-repo: nuitka-commander/nuitka-commander
          branch: master
      - name: 删除dist文件夹
        run: |
          cd ${{ github.workspace }}
          rm -rf ./dist
          rm -rf ./nuitka-commander
          ls -a
      # 这可以做一些其他特殊的所需处理
      - name: 为本地运行构建
        run: |
          npm run build:local_use
          mv ${{ github.workspace }}/dist/index.html ${{ github.workspace }}/dist/Nuitka-Commander.html
      - name: 读取版本号
        id: read_version
        run: |
          echo "VERSION=$(cat ${{ github.workspace }}/.github/workflows/scripts/version)" >> $GITHUB_ENV
      - name: 为Github发布release
        run: |
          gh release create $VERSION ${{ github.workspace }}/dist/Nuitka-Commander.html -F ${{ github.workspace }}/.github/workflows/scripts/CHANGELOG.md --latest -t $VERSION
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # todo
      - name: 为Gitee发布release
        run: echo todo
      # 重置更新日志并发布邮件提醒
      - name: ReCheckout
        uses: actions/checkout@v4
      - name: 重置更新日志
        run: |
          node ${{ github.workspace }}/.github/workflows/scripts/reset_changelog.js
          git config --global user.name "github action"
          git config --global user.email "action_bot@github.com"
          git add .
          git commit -m "Reset changelog"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Nuitka-Commander/nuitka-commander.github.io.git
