name: 构建并发布
on:
  workflow_dispatch:
    inputs:
    # 仅允许手动发布
    publish:
      description: '发布'
      required: true
      default: 'false'
jobs:
  check:
    name: 检查版本号
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: 加载storedData
        uses: actions/download-artifact@v2
        with:
          name: storedData
          path: ./
      - name: 检查版本号并输出
        run: node .github/workflows/scripts/check.js
      - name: 更新 storedData.json
        uses: actions/upload-artifact@v2
        with:
          name: storedData
          path: ./storedData.json
  build:
    runs-on: ubuntu-latest
    needs: check