name: 发布新版本
on:
  workflow_dispatch:
permissions: write-all
jobs:
  build_website:
    name: 构建网站
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: yarn-cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: 安装依赖
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: 构建网页
        run: yarn build:website
      - name: 发布到 GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: gh-pages
          build_dir: ./dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # 暂时Github和gitee构建文件一致，无需额外进行构建
      # build gitee
      - name: 推送到Gitee Page
        run: |
          git config --global user.name "erduotong"
          git config --global user.email "action_bot@github.com."
          git clone https://gitee.com/nuitka-commander/nuitka-commander.git
          cp -r ./dist/* ./nuitka-commander/
          cd ./nuitka-commander
          git add .
          git commit -m "Update from GitHub Actions"
          git push https://oauth2:${{ secrets.GITEE_TOKEN }}@gitee.com/nuitka-commander/nuitka-commander.git


