name: 发布新版本
on:
  workflow_dispatch:
permissions: write-all
jobs:
  pretreatment:
    name: 预处理
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: npm-cache
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name : 安装依赖
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name : 更新制作人员列表
        run: node ${{ github.workspace }}/.github/workflows/scripts/update_authors.js
      - name: 检查版本号冲突
        run: node ${{ github.workspace }}/.github/workflows/scripts/check_version.js
      # 其他预处理以后要用的时候在上方添加
      - name : Upload updated code as artifact
        uses: actions/upload-artifact@v2
        with:
          name: updated_code
          path: ./
  build_website:
    name : 为网站构建
    needs: pretreatment
    runs-on: ubuntu-latest
    steps:
      - name: Download Checkout
        uses: actions/download-artifact@v2
        with:
          name: updated_code
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: npm-cache
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name : 安装依赖
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name : 构建
        run: npm run build:website
      - name: 发布到 GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: gh-pages
          build_dir: ./dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 推送到Gitee
        run: |
          git config --global user.name "erduotong"
          git config --global user.email "action_bot@github.com."
          git clone https://gitee.com/nuitka-commander/nuitka-commander.git
          cp -r ./dist/* ./nuitka-commander/
          cd ./nuitka-commander
          git add .
          git commit -m "Update from GitHub Actions"
          git push https://oauth2:${{ secrets.GITEE_TOKEN }}@gitee.com/nuitka-commander/nuitka-commander.git
      - name: 部署Gitee Page
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: ${{secrets.GITEE_USERNAME}}
          gitee-password: ${{secrets.GITEE_PASSWORD}}
          gitee-repo: nuitka-commander/nuitka-commander
          gitee-branch: master


    build_local:
      name: 为本地使用构建(单文件)并发布
      needs: pretreatment
      runs-on: ubuntu-latest
      steps:
        - name: Download Checkout
          uses: actions/download-artifact@v2
          with:
            name: updated_code
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: 'npm'
        - name: npm-cache
          uses: actions/cache@v2
          id: npm-cache
          with:
            path: |
              **/node_modules
            key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-npm-
        - name: 安装依赖
          if: steps.npm-cache.outputs.cache-hit != 'true'
          run: npm ci
        - name: 构建
          run: npm run build:local_use




