name: build and publish
on:
  workflow_dispatch:
jobs:
  check:
    name: 检查版本号
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: 检查版本号并输出
        run: node .github/workflows/scripts/check.js
